name: TownyChatRemake
version: ${project.version}
main: net.laboulangerie.townychat.TownyChat
api-version: 1.19
authors: [PainOchoco]
depend: [Towny, PlaceholderAPI]
softdepend: [DiscordSRV]
commands:
    chat:
        permission: townychat.switch
        description: Switch between channels
        usage: /chat <channel>
    spy:
        permission: townychat.spy
        description: Spy on every town and nations channels
        usage: /spy

permissions:
    townychat.switch:
        default: true
    townychat.spy:
        default: op
    townychat.format.color:
        default: op
    townychat.format.bold:
        default: op
    townychat.format.underline:
        default: op
    townychat.format.italic:
        default: op
    townychat.format.strikethrough:
        default: op
    townychat.format.obfuscated:
        default: op
    townychat.format.rainbow:
        default: op
    townychat.format.all:
        default: op
    townychat.*:
        default: op
        children:
            townychat.switch: true
            townychat.spy: true
            townychat.format: true
            townychat.format.color: true
            townychat.format.bold: true
            townychat.format.underline: true
            townychat.format.italic: true
            townychat.format.strikethrough: true
            townychat.format.obfuscated: true
            townychat.format.rainbow: true
            townychat.format.all: true
